version: "3.7"

services: 
    php:
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
        links:
            - db
    composer:
        image: composer:latest
        volumes:
             - .:/var/www/html
        command: composer install -d /var/www/html
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_USER: pocuser
            MYSQL_PASSWORD: pocuser
            MYSQL_DATABASE: pocuser
            MYSQL_ROOT_PASSWORD: pocuser
        ports:
            - "3306:3306"