<?php $this->layout('templates/index', ['title' => 'User List']) ?>

<h1 class="mt-5">Usuários cadastrados</h1>

<div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome Completo</th>
                <th scope="col">Email</th>
                <th scope="col">CPF</th>
                <th scope="col">Telefone</th>
                <th scope="col">Editar</th>
                <th scope="col">Remover</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($usersList as $user): ?>
                <tr>
                    <th scope="row"><?= $user->getId() ?></th>
                    <td><?= $user->getName() ?></td>
                    <td><?= $user->getEmail() ?></td>
                    <td><?= $user->getCpf() ?></td>
                    <td><?= $user->getPhone() ?></td>
                    <td><a href="/edit/<?= $user->getId() ?>">Editar</a></td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>