<?php $this->layout('templates/index', ['title' => 'User Profile']) ?>

<h1 class="mt-5">Usuários cadastrados</h1>

<div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome Completo</th>
                <th scope="col">Email</th>
                <th scope="col">CPF</th>
                <th scope="col">Telefone</th>
                <th scope="col">Editar</th>
                <th scope="col">Remover</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Mark Lark</td>
                <td>lark@mark.com</td>
                <td>1111111111</td>
                <td>47 3355-5555</td>
            </tr>
            <tr>
                <th scope="row">1</th>
                <td>Mark Lark</td>
                <td>lark@mark.com</td>
                <td>1111111111</td>
                <td>47 3355-5555</td>
            </tr>
            <tr>
                <th scope="row">1</th>
                <td>Mark Lark</td>
                <td>lark@mark.com</td>
                <td>1111111111</td>
                <td>47 3355-5555</td>
            </tr>
        </tbody>
    </table>
</div>